[colors.selection]
background = "0x3e4452"
text = "CellForeground"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 17.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "ComicShannsMono Nerd Font"
style = "Regular"

[scrolling]
history = 15000

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[window]
opacity = 0.8
blur = true
option_as_alt = "OnlyLeft"
dynamic_padding = true
decorations = "full"
title = "craftznake"
dynamic_title = false

[window.padding]
x = 8
y = 0

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
# Send CSI u sequence for Ctrl+i to distinguish it from Tab
key = "i"
mods = "Control"
chars = "\u001b[105;5u"

# Disable some default key bindings
[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "F"
mods = "Command|Control"
action = "ReceiveChar"

[mouse]
hide_when_typing = true

[general]
#:schema https://raw.githubusercontent.com/distinction-dev/alacritty-schema/main/alacritty/reference.json

live_config_reload = true
import = ["~/.config/alacritty/themes/gruvbox.toml"]
